FROM jenkins/jenkins:2.319.3-lts-jdk11
ENV JAVA_OPTS-Djenkins.install.runSetupWizard=false
ENV CASC_JENKINS_CONFIG /usr/share/jenkins/ref/casc.yml
COPY /home/vagrant/jenkins/plugins.txt /usr/share/jenkins/ref
